import type { SearchItem } from './types'

export const SEARCH_DATA: SearchItem[] = [
  {
    id: '1',
    title: 'React 19 新特性完全指南',
    description: '深入了解 React 19 的 Actions、use() Hook、文档元数据等新功能，助你快速上手最新版本。',
    category: 'article',
    tags: ['React', '前端', 'JavaScript'],
    url: '#',
    date: '2026-03-15',
  },
  {
    id: '2',
    title: 'TypeScript 5.7 类型系统进阶',
    description: '探索 TypeScript 最新版本的类型推断改进、装饰器支持和性能优化技巧。',
    category: 'article',
    tags: ['TypeScript', '类型系统'],
    url: '#',
    date: '2026-02-20',
  },
  {
    id: '3',
    title: 'Vite 构建工具实战教程',
    description: '从零开始学习 Vite，涵盖项目配置、插件开发、生产环境优化等核心内容。',
    category: 'video',
    tags: ['Vite', '构建工具', '前端工程化'],
    url: '#',
    date: '2026-01-10',
  },
  {
    id: '4',
    title: 'AI 驱动的代码搜索工具',
    description: '使用自然语言描述即可在代码库中精准定位函数、类和接口，大幅提升开发效率。',
    category: 'tool',
    tags: ['AI', '搜索', '开发工具'],
    url: '#',
    date: '2026-04-01',
  },
  {
    id: '5',
    title: '2026 年前端技术趋势报告',
    description: '全面分析 Server Components、边缘计算、WebAssembly 等前沿技术的发展方向。',
    category: 'news',
    tags: ['趋势', '前端', '2026'],
    url: '#',
    date: '2026-03-28',
  },
  {
    id: '6',
    title: 'CSS Grid 布局大师课',
    description: '通过实战项目掌握 CSS Grid 的高级用法，包括子网格、命名区域和响应式设计。',
    category: 'video',
    tags: ['CSS', '布局', '响应式'],
    url: '#',
    date: '2025-12-05',
  },
  {
    id: '7',
    title: 'Node.js 性能优化最佳实践',
    description: '从事件循环、内存管理到集群模式，系统讲解 Node.js 应用性能调优方法。',
    category: 'article',
    tags: ['Node.js', '性能', '后端'],
    url: '#',
    date: '2026-02-14',
  },
  {
    id: '8',
    title: '智能搜索引擎 API 集成',
    description: '快速接入 Elasticsearch、Algolia 等搜索引擎，实现毫秒级全文检索体验。',
    category: 'tool',
    tags: ['搜索', 'API', 'Elasticsearch'],
    url: '#',
    date: '2026-03-20',
  },
  {
    id: '9',
    title: 'Web 无障碍设计规范',
    description: '遵循 WCAG 2.2 标准，打造对所有用户友好的可访问 Web 应用。',
    category: 'article',
    tags: ['无障碍', 'UX', 'WCAG'],
    url: '#',
    date: '2026-01-25',
  },
  {
    id: '10',
    title: 'Rust 与 WebAssembly 融合开发',
    description: '利用 Rust 编写高性能 WASM 模块，在浏览器中实现接近原生的计算速度。',
    category: 'news',
    tags: ['Rust', 'WASM', '性能'],
    url: '#',
    date: '2026-04-05',
  },
  {
    id: '11',
    title: '自动化测试框架对比',
    description: '横向对比 Playwright、Cypress、Puppeteer 三大 E2E 测试框架的优劣与适用场景。',
    category: 'article',
    tags: ['测试', '自动化', 'E2E'],
    url: '#',
    date: '2026-02-08',
  },
  {
    id: '12',
    title: '实时数据可视化仪表盘',
    description: '使用 D3.js 和 WebSocket 构建动态更新的数据大屏，支持多种图表类型。',
    category: 'tool',
    tags: ['可视化', 'D3.js', '实时数据'],
    url: '#',
    date: '2026-03-12',
  },
]

export const HOT_KEYWORDS = [
  'React',
  'TypeScript',
  'AI 搜索',
  '前端趋势',
  '性能优化',
  '自动化测试',
]
